### ISSUE TITLE
Openssl warning when filling partition with noise

### ISSUE THREAD

**Issue by Gullumluvl** [rdkr/ubuntu-lvm-on-luks#5]
This is of minor concern, but for information:
I manually ran the `openssl enc` command from the `noise` function, and obtained the following warning:

```
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
```

I have "OpenSSL 1.1.1f  31 Mar 2020" on Xubuntu 20.04.2 LTS (Focal).

---
P.S.: I also choose to specify a different cipher algo in the luksFormat command ("aes-xts-plain64"), and I am not sure how to tell openSSL to use this one, but is it absolutely necessary that the noise and luksFormat use the exact same algo?

**Comment by rdkr** [comment]
the key derivation / encryption method used by openssl don't really matter as it is only used in the process of generating random data to fill the partition. openssl is used instead of reading directly from `/dev/urandom`, etc. just because it's quicker.

once the (optional) step of filling the partition with noise is done, the key is never used again nor the generated data decrypted; if they were, it would just be 0s.

the luks container then exist on top of that random data, and you can use your preferred settings for that, unrelated to the noise.

i'll update the command to not cause misleading warnings though, thanks!
